version: '3'

services:
    flask-rest:
        build: ./backend
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/backend
        environment:
            FLASK_RUN_HOST: 0.0.0.0
            FLASK_CONFIG_ENVIRONMENT: conf.DevelopmentConfig

    react-app:
        build: ./client
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
        stdin_open: true
        tty: true
